version: '3.8'

services:

  app:
    restart: always
    image: $DOCKER_REGISTRY/dev/app:$CI_COMMIT_SHA
    container_name: dev_ml_service
    ports:
      - "8004:80"
    environment:
      - MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
      - MLFLOW_S3_ENDPOINT_URL=$MLFLOW_S3_ENDPOINT_URL
