stages:

  raw_train_test_split:
    cmd: python .\src\data\raw_train_test_split.py .\data\raw\train.csv .\data\interim\split_train.csv .\data\interim\split_test.csv --n_splits=${train_test_split.n_splits}
    deps:
      - .\data\raw\train.csv
      - .\src\data\raw_train_test_split.py
    outs:
      - .\data\interim\split_train.csv
      - .\data\interim\split_test.csv


  generate_pairs_train:
    cmd: python .\src\data\generate_pairs.py .\data\interim\split_train.csv .\data\interim\split_train_pairs.csv .\reports\metrics_of_split_train_pairs.json --get_metrics=true
    deps:
      - .\data\interim\split_train.csv
      - .\src\data\generate_pairs.py
    outs:
      - .\data\interim\split_train_pairs.csv
    metrics:
      - .\reports\metrics_of_split_train_pairs.json:
          cache: false


  build_pair_features_train:
    cmd: python .\src\features\build_pair_features.py .\data\interim\split_train_pairs.csv .\data\processed\split_train_pair_feautures.csv true
    deps:
      - .\data\interim\split_train_pairs.csv
      - .\src\features\build_pair_features.py
    outs:
      - .\data\processed\split_train_pair_feautures.csv


  train_model:
    cmd: python .\src\models\train_model.py .\models\model_on_split_df.pkl --pair_feautures_dataset_path .\data\processed\split_train_pair_feautures.csv
    deps:
      - .\data\processed\split_train_pair_feautures.csv
      - .\src\models\train_model.py
    outs:
      - .\models\model_on_split_df.pkl


  generate_pairs_test:
    cmd: python .\src\data\generate_pairs.py .\data\interim\split_test.csv .\data\interim\split_test_pairs.csv .\reports\metrics_of_split_test_pairs.json --get_metrics=true
    deps:
      - .\data\interim\split_test.csv
      - .\src\data\generate_pairs.py
    outs:
      - .\data\interim\split_test_pairs.csv
    metrics:
      - .\reports\metrics_of_split_test_pairs.json:
          cache: false


  build_pair_features_test:
    cmd: python .\src\features\build_pair_features.py .\data\interim\split_test_pairs.csv .\data\processed\split_test_pair_feautures.csv true
    deps:
      - .\data\interim\split_test_pairs.csv
      - .\src\features\build_pair_features.py
    outs:
      - .\data\processed\split_test_pair_feautures.csv


  predict_model:
    cmd: python .\src\models\predict_model.py .\models\model_on_split_df.pkl .\data\interim\split_test.csv .\data\processed\submission_pred_split.csv 
        --pair_feautures_dataset_path .\data\processed\split_test_pair_feautures.csv
    deps:
      - .\models\model_on_split_df.pkl
      - .\data\interim\split_test.csv
      - .\data\processed\split_test_pair_feautures.csv
      - .\src\models\predict_model.py
    outs:
      - .\data\processed\submission_pred_split.csv


  evaluate:
    cmd: python .\src\models\evaluate.py .\data\interim\split_test.csv .\data\processed\submission_pred_split.csv .\reports\metrics_of_split_test_final.json
    deps:
      - .\data\interim\split_test.csv
      - .\data\processed\submission_pred_split.csv
      - .\src\models\evaluate.py
    metrics:
      - .\reports\metrics_of_split_test_final.json:
          cache: false